name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xcode_version: [ latest, 14 ]
        arch: [ x86_64, arm64 ]  # Desteklenen mimarileri ekledim
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0        
      with:
        xcode-version: ${{ matrix.xcode_version }}

    - name: Build
      run: swift build -v -c release --arch ${{ matrix.arch }}  # Mimariyi doğru kullandık
