name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        xcode_version: [ latest-stable, 14 ]
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0        
      with:
        xcode-version: ${{ matrix.xcode_version }}

    - name: Build
      run: swift build -v -c release --triple ${{ matrix.arch }}
